CREATE TABLE `sc_material` (
  `id` bigint NOT NULL COMMENT '主键id，存量prod_material.id 迁移此',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '物料编码,存量迁移spec_code',
  `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '物料名称',
  `short_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '物料简称',
  `type` tinyint(1) DEFAULT '0' COMMENT '物料类型（0:一般商品，1:宣传物料）默认0',
  `material_brand` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '物料-品牌',
  `material_brand_model` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '物料-品牌型号',
  `stock_unit_id` bigint DEFAULT NULL COMMENT '基础规格单位(最小库存单位)',
  `category_id` bigint NOT NULL COMMENT '分类id',
  `operating_brand_ids` varchar(64) DEFAULT NULL COMMENT '冗余:集团经营品牌id',
  `storage_type_id` bigint NOT NULL COMMENT '存放类型id',
  `storage_type_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '存放类型名称',
  `smart_device` tinyint(1) DEFAULT '0' COMMENT '是否智能设备（1：是，0：否）默认0',
  `shop_sell` tinyint DEFAULT '1' COMMENT '是否报货物料{1:是,0:否},默认:是',
  `inventory_adjust_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '库存调整类型',
  `guarantee_period` decimal(10, 2) DEFAULT NULL COMMENT '保质期',
  `guarantee_period_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '保质期周期单位',
  `measured_quantity` decimal(10, 2) DEFAULT NULL COMMENT '计量数量',
  `measured_unit_id` bigint DEFAULT NULL COMMENT '计量单位',
  `cost_quantity` decimal(10, 2) DEFAULT NULL COMMENT '成本-消耗数量\n',
  `cost_unit_id` bigint DEFAULT NULL COMMENT '成本-单位\n',
  `sort` int DEFAULT '0' COMMENT '排序',
  `state` tinyint(1) DEFAULT '1' COMMENT '物料状态(1:可用,0:不可用）默认1',
  `material_net_rate` decimal(10, 2) DEFAULT NULL COMMENT '净料率',
  `tea_pack_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '茶叶包装码',
  `main_img_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '预留,主图地址',
  `img_urls` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '预留,图片地址',
  `tag` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '物料标签（Json类型，数组）',
  `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '描述',
  `ext` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扩展字段（Json类型）',
  `flag` bigint DEFAULT NULL COMMENT '物料标识,MaterialFlag',
  `old_material_spec_id` bigint DEFAULT NULL COMMENT '迁移阶段，过渡用。兼容下游使用material_spec_id 业务,比如效期贴、智能设备等业务',
  `old_material_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '迁移阶段，过渡用。兼容下游使用material_code 业务,比如产品配方、效期贴、智能设备等业务',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除（1:是，0:否）默认0',
  `create_user` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`),
  KEY `idx_material_category_id` (`category_id`),
  KEY `idx_material_name` (`name`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '物料表'
;

CREATE TABLE `sc_packing` (
  `id` bigint NOT NULL COMMENT '主键id',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0' COMMENT '包装规格编码',
  `name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0' COMMENT '包装规格名称',
  `packing_spec` varchar(64) DEFAULT NULL COMMENT '包装规格转换结果描述',
  `material_id` bigint NOT NULL DEFAULT '0' COMMENT '关联物料id',
  `material_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0' COMMENT '冗余,物料编码',
  `parent_id` bigint DEFAULT '0' COMMENT '上级包装规格id,根=0',
  `parent_code` varchar(64) DEFAULT NULL COMMENT '冗余,上级包装规格code,根=null',
  `packing_unit_id` bigint DEFAULT '0' COMMENT '包装单位id',
  `stock_unit_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '冗余,基础规格单位名称',
  `packing_unit_name` varchar(32) DEFAULT NULL COMMENT '冗余,包装单位名称',
  `stock_unit_id` bigint DEFAULT NULL COMMENT '基础规格单位id',
  `conversion_rate` decimal(12, 2) DEFAULT NULL COMMENT '跟上线规格换算比率',
  `stock_unit_conversion_rate` decimal(10, 2) DEFAULT NULL COMMENT '跟基础规格换算比率\n',
  `scenario_codes` varchar(255) DEFAULT NULL COMMENT '关联场景code',
  `sort` int DEFAULT '10' COMMENT '排序',
  `ext` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扩展字段（Json类型）',
  `out_material_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '外部系统物料编码',
  `state` int DEFAULT '1' COMMENT '有效状态{1:有效,0:无效}',
  `deleted` tinyint DEFAULT NULL COMMENT '逻辑删除',
  `update_user` varchar(64) DEFAULT NULL COMMENT '最后修改人',
  `create_user` varchar(64) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `udx_packing_code` (`code`) USING BTREE,
  KEY `idx_material_id` (`material_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '物料包装规格'
;

CREATE TABLE `sc_product` (
  `id` bigint NOT NULL COMMENT '主键id',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '报货物料编码',
  `name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '报货物料名称',
  `front_category_id` bigint DEFAULT NULL COMMENT '报货物料-类目id(前台类目)',
  `category_id` bigint DEFAULT NULL COMMENT '冗余,后台分类id',
  `material_id` bigint NOT NULL COMMENT '关联物料id',
  `material_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '冗余,物料编码',
  `material_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '冗余,物料名称',
  `packing_id` bigint DEFAULT NULL COMMENT '关联物料包装规格id',
  `packing_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '冗余,物料包装规格code',
  `packing_spec` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'packing_spec, (销售规格)完整关系包装规格',
  `material_net_rate` decimal(12, 2) DEFAULT NULL COMMENT '净料率',
  `material_brand_id` bigint DEFAULT NULL COMMENT '物料品牌id',
  `cost_conversion_rate` decimal(12, 2) DEFAULT NULL COMMENT '冗余,成本换算率',
  `sell_mode` tinyint DEFAULT '0' COMMENT '售卖方式（0:正常，1:预售）默认0',
  `storage_type_id` bigint DEFAULT NULL COMMENT '存放类型id',
  `type` tinyint DEFAULT '0' COMMENT '商品类型（0:一般商品，1:宣传物料）默认0',
  `business_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'NORMAL' COMMENT '业务类型 ，字典: ScProductBusinessTypeEnum',
  `smart_device` tinyint(1) DEFAULT '0' COMMENT '冗余,是否智能设备{1:是,0:否}默认0',
  `install_model` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '设备安装方式',
  `bar_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '条形码',
  `stock_unit_id` bigint DEFAULT NULL COMMENT '冗余,基础单位',
  `booking_unit_id` bigint DEFAULT NULL COMMENT '报货单位ID',
  `packing_unit_id` bigint DEFAULT NULL COMMENT '冗余,包装规格单位ID',
  `min_buy_unit_id` bigint DEFAULT NULL COMMENT '计价单位(金蝶计价单位id)',
  `min_buy_num` decimal(10, 2) DEFAULT '1.00' COMMENT '起购数量',
  `step` int DEFAULT '1' COMMENT '步长，默认1',
  `sale_amount` decimal(15, 6) DEFAULT NULL COMMENT '报货单价(门店宝)',
  `purchase_amount` decimal(15, 6) DEFAULT NULL COMMENT '采购价(进价)',
  `show_packing_spec` tinyint(1) DEFAULT '0' COMMENT '是否展示箱规',
  `agent_profit` tinyint(1) DEFAULT '0' COMMENT '代理返点',
  `supplier_id` bigint DEFAULT NULL COMMENT '供应商id',
  `main_img` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '主图地址',
  `img_urls` varchar(1024) DEFAULT NULL COMMENT '图片地址（Json类型，数组）',
  `tag` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商品标签（Json类型，数组）',
  `service_fee` decimal(15, 6) DEFAULT NULL COMMENT '服务费',
  `in_menu` tinyint(1) DEFAULT '0' COMMENT '是否关联报货菜单(1:是,0:否)默认0',
  `menu_sort` int DEFAULT '0' COMMENT '报货菜单排序',
  `sort` int DEFAULT '0' COMMENT '排序',
  `up` tinyint(1) DEFAULT '1' COMMENT '是否上架{1:是,0:否}默认1',
  `sellable` tinyint(1) DEFAULT '1' COMMENT '是否可售(前台可见),{1:是,0:否}默认1',
  `combined` tinyint(1) DEFAULT '0' COMMENT '是否是组合商品{1:是,0:否}默认0',
  `main_product` tinyint(1) DEFAULT '0' COMMENT '是否主商品{1:是,0:否}',
  `day_delivery` tinyint(1) DEFAULT '0' COMMENT '是否可日配{1:是,0:否}默认0',
  `latest_issue_info` json DEFAULT NULL COMMENT '最新发布信息（Json类型）',
  `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '描述',
  `ext` varchar(5000) DEFAULT NULL COMMENT '扩展字段（Json类型）',
  `flag` bigint DEFAULT '0' COMMENT '标记',
  `old_material_spec_id` bigint DEFAULT NULL COMMENT '用于迁移,兼容老物料规格id',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除{1:是,0:否}默认0',
  `create_user` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(64) DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_code` (`code`),
  KEY `idx_material_code` (`material_code`),
  KEY `idx_packing_code` (`packing_code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '报货物料'
;
